runtime: python38

instance_class: F4

entrypoint: "gunicorn -b:$PORT main:app"

env_variables:
        APP_SETTINGS: "config.ProductionConfig"

handlers:
   - url: /static
     static_dir: static

default_expiration: "30s"
