runtime: python38

instance_class: F4

entrypoint: "gunicorn -b:$PORT main:app"

env_variables:
        APP_SETTINGS: "config.ProductionConfig"

#handlers:
# Matches requests to /images/... to files in static/images/...
#- url: /images
#  static_dir: static/images

#- url: /.*
#  secure: always
#  redirect_http_response_code: 301
#  script: auto
